# UV Installation

We are going to use <code>uv</code> to install the project dependencies and libraries. To install run the command below:

In [ ]:
# On Windows.
powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"

Then initialize uv with the following command and setup:

In [ ]:
uv init
uv venv #To create a virtual environment
.venv\Scripts\Activate #To activate virtual environment


Note: you may need to restart the kernel to use updated packages.


error: Project is already initialized in `d:\PyTorch` (`pyproject.toml` file exists)


# Install Pytorch

To install <code>PyTorch</code> use the code given below, and since we are using <code>uv</code> the following powershell command is in uv

The device i'm currently using has an intel arc gpu so the command is for intel gpu,

In [ ]:
uv pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/xpu

Note: you may need to restart the kernel to use updated packages.


Audited 3 packages in 9ms


If you hav a NVIDIA gpu then follow the steps below:

>Ensure CUDA Toolkit is installed and NVIDIA drivers are up-to-date,
>Determine the appropriate CUDA version for your system from the PyTorch website's "Get Started" section (e.g.,  CUDA 12.1). Then, install PyTorch, torchvision, and torchaudio using uv, specifying the correct CUDA index URL:


Replace cu121 with your specific CUDA version (e.g., cu118, cu124). install ipykernel.

In [ ]:
uv add torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 

Install basic python libraries such as<code>numpy pandas matplotlib</code>

In [1]:
uv add numpy pandas matplotlib

Note: you may need to restart the kernel to use updated packages.


Resolved 112 packages in 2.41s
 Downloaded fonttools
 Downloaded pillow
 Downloaded matplotlib
 Downloaded pandas
 Downloaded numpy
Prepared 5 packages in 13.89s
Uninstalled 2 packages in 125ms
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 10 packages in 1.25s
 + contourpy==1.3.3
 + cycler==0.12.1
 + fonttools==4.61.0
 + kiwisolver==1.4.9
 + matplotlib==3.10.7
 - numpy==2.3.3
 + numpy==2.3.5
 + pandas==2.3.3
 - pillow==11.3.0
 + pillow==12.0.0
 + pyparsing==3.2.5
 + pytz==2025.2


In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
print(torch.__version__)

2.9.1+xpu


# Introdution to Tensors

### Creating Tensor

PyTorch tensors are created using `torch.tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

In [7]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [9]:
#Get tensor back as python int
scalar.item()

7

In [11]:
#vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [12]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

In [14]:
#MATRIX
MATRIX = torch.tensor([[7, 7],
                      [9, 8]])
MATRIX

tensor([[7, 7],
        [9, 8]])

In [16]:
MATRIX.ndim

2

In [17]:
MATRIX[1]

tensor([9, 8])

In [18]:
MATRIX.shape

torch.Size([2, 2])

In [19]:
#TENSOR
TENSOR = torch.tensor([[[2, 3, 5],
                        [4, 6, 9],
                        [8, 77, 43]]])
TENSOR

tensor([[[ 2,  3,  5],
         [ 4,  6,  9],
         [ 8, 77, 43]]])

In [20]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([1, 3, 3])

In [32]:
TENSOR[0]

tensor([[ 2,  3,  5],
        [ 4,  6,  9],
        [ 8, 77, 43]])

In [31]:
TENSOR[0,2]

tensor([ 8, 77, 43])

### Random Tensors

Why rabdom tensors?

Random tensors are important becausevthe way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

